# Generated by Django 5.0.3 on 2024-03-25 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=100)),
                ('dealership_details', models.CharField(max_length=200)),
            ],
        ),
    ]
