# Generated by Django 5.0.3 on 2024-03-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sale',
            name='dealership_details',
            field=models.CharField(max_length=200),
        ),
    ]
