# Generated by Django 5.0.3 on 2024-04-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='customer_contact',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='warranty',
            name='customer_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='warranty',
            name='dealership_details',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
